export const polkadotChains = {
  polkadot: {
    display: "Polkadot",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fpolkadot.png&w=96&q=75",
    paraChainId: -1,
    ss58Prefix: 0,
  },
  bifrostPolkadot: {
    display: "BifrostPolkadot",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fpolkadot.png&w=96&q=75",
    paraChainId: 2030,
    ss58Prefix: 0,
  },
  statemint: {
    display: "Statemint",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fstatemine.png&w=96&q=75",
    paraChainId: 1000,
    ss58Prefix: 0,
  },
  acala: {
    display: "Acala",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Facala.png&w=96&q=75",
    paraChainId: 2000,
    ss58Prefix: 10,
  },
  parallel: {
    display: "Parallel",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fparallel.png&w=96&q=75",
    paraChainId: 2012,
    ss58Prefix: 172,
  },
  moonbeam: {
    display: "Moonbeam",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fmoonbeam.png&w=96&q=75",
    paraChainId: 2004,
    ss58Prefix: 1284,
  },
  interlay: {
    display: "Interlay",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Finterlay.png&w=96&q=75",
    paraChainId: 2032,
    ss58Prefix: 2032,
  },
  astar: {
    display: "Astar",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fastar.png&w=96&q=75",
    paraChainId: 2006,
    ss58Prefix: 5,
  },
  hydradx: {
    display: "HydraDX",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fhydra.png&w=96&q=75",
    paraChainId: 2034,
    ss58Prefix: 63,
  },
  zeitgeist: {
    display: "Zeitgeist",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fzeitgeist.png&w=96&q=75",
    paraChainId: 2092,
    ss58Prefix: 73,
  },
  unique: {
    display: "Unique Network",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Funique.png&w=96&q=75",
    paraChainId: 2037,
    ss58Prefix: 7391,
  },
  centrifuge: {
    display: "Centrifuge",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2031,
    ss58Prefix: 36,
  },
  phala: {
    display: "Phala",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2035,
    ss58Prefix: 36, // *
  },
  crust: {
    display: "Crust",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2008,
    ss58Prefix: 36, // *
  },
  manta: {
    display: "Manta",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2104,
    ss58Prefix: 36, // *
  },
  darwinia: {
    display: "Darwinia",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2046,
    ss58Prefix: 36, // *
  },
  oak: {
    display: "Oak",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2090,
    ss58Prefix: 36, // *
  },
  invarch: {
    display: "Invarch",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 3340,
    ss58Prefix: 117, 
  },
  kilt: {
    display: "Kilt",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2086,
    ss58Prefix: 63, 
  },
  subsocial: {
    display: "Subsocial",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2101,
    ss58Prefix: 63, 
  },
  pendulum: {
    display: "Pendulum",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2094,
    ss58Prefix: 63, 
  },
  nodle: {
    display: "Nodle",
    type: "substrate",
    icon: "https://resources.acala.network/_next/image?url=%2Fnetworks%2Fcentrifuge.png&w=96&q=75",
    paraChainId: 2026,
    ss58Prefix: 63, 
  },
};
